services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - minha_rede
    environment:
      - REDIS_HOST=redis
      
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
    networks:
      - minha_rede

volumes:
  redis_data:

networks:
  minha_rede:
